#!/usr/bin/env python3

import os, sys, re

def blocks(ipblocks, cidr):
	if len(ipblocks) == 0: return 0
	cidr2 = int(ipblocks[0].split('/')[1])
	if cidr2 > int(cidr):
		print(ipblocks[0].strip() + " " * (26 - len(ipblocks[0].strip())) + '0')
		return blocks(ipblocks[1:], cidr)
	else: 
		print (ipblocks[0].strip() + " " * (26 - len(ipblocks[0].strip())) + str(2**(int(cidr) - cidr2)))
		return (2**(int(cidr) - cidr2)) + blocks(ipblocks[1:], cidr)

print("Block\t\t\t/" + sys.argv[2] + "s")
print("Total /" + sys.argv[2] + "s:\t\t "+ str(blocks(list(open(sys.argv[1], 'r')), sys.argv[2])))
