#!/bin/bash
if [[ "$1" =~ \-.*c.* ]]; then
	clear=true
fi
if [[ "$1" =~ \-.*l.* ]]; then
	lacp=true
fi
if [[ "$1" =~ \-.*i.* ]]; then
	load=true
fi
if [[ "$1" =~ \-.*n.* ]]; then
	noshut=true
fi
if [[ "$1" =~ \-.*s.* ]]; then
	shut=true
fi
if [[ "${@: 1}" =~ \-d ]]; then
	description=true
	i=1
	for a in $@; do
		if [[ "[$a]" =~ \-d ]]; then
			i=$(( $i + 1 ))
			rhost=`echo "${@:$i:1}"`
			i=$(( $i + 1 ))
			rstart=`echo "${@:$i:1}"`
			i=$(( $i + 1 ))
			rnum=`echo "${@:$i:1}"`
		else
			i=$(( $i + 1 ))
		fi
	done
	IFS='/' read -a d <<< "$rstart"
	o=${d[3]}
fi
if [[ "${@: 1}" =~ \-b ]]; then
	bundle=true
	i=1
	for a in $@; do
		if [[ "[$a]" =~ \-b ]]; then
			i=$(( $i + 1 ))
			bnum=`echo "${@:$i:1}"`
		else
			i=$(( $i + 1 ))
		fi
	done
fi
i=0
line="interface TenGigE"
num=`echo "${@:$#}"`
c=$(( $# - 1 ))
card=`echo "${@:$c:1}"`
s=$(( $# - 2 ))
start=`echo "${@:$s:1}"`
IFS='/' read -a l <<< "$start"
n=${l[3]}
while [ "$i" -lt "$num" ]; do
	if [ "$n" -ge "$card" ]; then
		l[1]=$(( ${l[1]} + 1 ))
		n=0
	fi
	if [ ! -z "$d" ] && [ "$o" -ge "$rnum" ]; then
		d[1]=$(( ${d[1]} + 1 ))
		o=0
	fi
	if [ $clear ]; then
		echo "$line" | sed 's/\(.*\)/no\ \1'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'/'
	fi
	if [ $description ]; then
		echo "$line" | sed 's/$/'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ description\ tge\ to\ '$rhost'\ tge'${d[0]}'\/'${d[1]}'\/'${d[2]}'\/'$o'/'
	fi
	if [ $bundle ]; then
		echo "$line" | sed 's/$/'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ bundle\ id\ '$bnum'\ mode\ active/'
	fi
	if [ $lacp ]; then
		echo "$line" | sed 's/$/'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ lacp\ period\ short/'
	fi
	if [ $load ]; then
		echo "$line" | sed 's/$/'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ load\-interval\ 30/'
	fi
	if [ $noshut ]; then
		echo "$line" | sed 's/\(.*\)/no\ \1'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ shutdown/'
	fi
	if [ $shut ]; then
		echo "$line" | sed 's/\(.*\)/\1'${l[0]}'\/'${l[1]}'\/'${l[2]}'\/'$n'\ shutdown/'
	fi
	i=$(( $i + 1 ))
	n=$(( $n + 1 ))
	o=$(( $o + 1 ))
done
